Repository kakao-tech-campus-2nd-step3/Team15_FE, pull requests merged in 2024-11, with the labels that each got.

#94 Feat(#93): 마이페이지 기본 구조
  src/assets/Mypage/point.svg
  src/components/common/Sidebar/index.tsx
  src/components/feature/mypage/section/Navber/index.tsx
  src/components/feature/mypage/section/UserInfo/index.tsx
  src/pages/MyPage/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: 🛠️Feature

#97 Style(95): 랜딩 페이지 landing items section CSS 변경
  src/components/feature/home/Favorite/index.tsx
  src/components/feature/home/Story/index.tsx
Labels: 🧑🏻‍🎨Style

#98 Style(#95): CSS 수정
  src/components/common/Sidebar/index.tsx
  src/components/common/overlay/index.tsx
  src/components/feature/feed/post/Card/index.tsx
Labels: 🧑🏻‍🎨Style

#104 Feat(#103): Private router 추가
  src/pages/MyPage/index.tsx
  src/routes/PrivateRoute/index.tsx
  src/routes/index.tsx
Labels: 🛠️Feature

#105 Style(#95): 피드 카드 content 프리뷰 20글자 제한
  src/components/feature/feed/post/Card/index.tsx
  src/components/feature/feed/section/FeedItems/index.tsx
Labels: 🧑🏻‍🎨Style

#106 Feat(#81) challenge 구현
  package-lock.json
  package.json
  src/assets/defaultImage.png
  src/components/common/Header/index.tsx
  src/components/common/Modal/index.tsx
  src/components/feature/challegeDetail/Contents/index.tsx
  src/components/feature/challegeDetail/Intro/index.tsx
  src/components/feature/challenge/post/Card/index.tsx
  src/components/feature/challenge/section/ChallengeForm/index.tsx
  src/components/feature/challenge/section/ChallengeItems/index.tsx
  src/components/feature/challenge/section/NavBar/index.tsx
  src/components/feature/challenge/section/WriteButton/index.tsx
  src/components/feature/images/UploadImage/index.tsx
  src/components/feature/modals/challenges/PostChallenge/index.tsx
  src/components/feature/modals/stories/PostStory/index.tsx
  src/pages/Challenge/index.tsx
  src/pages/ChallengeDetail/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/types/index.tsx
  src/util/hooks/useChallengeFilter/index.tsx
Labels: 🛠️Feature

#107 Feat(89): Story 작성 모달
  src/components/feature/modals/stories/PostStory/index.tsx
Labels: 🛠️Feature

#115 Feat(#81): 챌린지 참여 페이지 구현
  src/App.tsx
  src/api/instance/index.ts
  src/components/common/Avatar/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Grid/index.stories.tsx
  src/components/common/Grid/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/Image/index.stories.tsx
  src/components/common/Image/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/layouts/Container/index.tsx
  src/components/feature/booksearch/BookCard/index.tsx
  src/components/feature/booksearch/Books/index.tsx
  src/components/feature/booksearch/SearchBox/index.tsx
  src/components/feature/challegeDetail/Contents/index.tsx
  src/components/feature/challegeDetail/Intro/index.tsx
  src/components/feature/challegeDetail/Section/Navbar/index.tsx
  src/components/feature/challegeDetail/Verification/index.tsx
  src/components/feature/challenge/post/Card/index.tsx
  src/components/feature/challenge/section/ChallengeForm/index.tsx
  src/components/feature/challenge/section/ChallengeItems/index.tsx
  src/components/feature/challenge/section/NavBar/index.tsx
  src/components/feature/challenge/section/WriteButton/index.tsx
  src/components/feature/feed/section/WriteButton/index.tsx
  src/components/feature/feed/section/contentDetail/StoryDetail/index.tsx
  src/components/feature/home/Card/index.tsx
  src/components/feature/home/Challege/index.tsx
  src/components/feature/home/Footer/index.tsx
  src/components/feature/home/Header/index.tsx
  src/components/feature/home/Section/Landing-items/index.tsx
  src/components/feature/home/Welcome/index.tsx
  src/components/feature/home/Welcome/logo.tsx
  src/components/feature/images/UploadImage/index.tsx
  src/components/feature/login/LoginButton/index.tsx
  src/components/feature/modals/challenges/PostChallenge/index.tsx
  src/components/feature/modals/stories/ContentDetail/index.tsx
  src/components/feature/modals/verification/PostVefication/index.tsx
  src/components/feature/mypage/section/Navber/index.tsx
  src/components/feature/mypage/section/UserInfo/index.tsx
  src/index.css
  src/index.tsx
  src/pages/BookSearch/index.tsx
  src/pages/Challenge/index.tsx
  src/pages/ChallengeDetail/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/provider/Auth/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/types/Custom/svg.d.ts
  src/types/index.tsx
  src/util/hooks/useChallengeFilter/index.tsx
Labels: 🛠️Feature

#117 Feat(#116): 책 작성 기능 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/feature/booksearch/Books/index.tsx
  src/components/feature/feed/section/FeedItems/index.tsx
  src/components/feature/feed/section/WriteButton/index.tsx
  src/components/feature/modals/favbooks/PostFavBook/index.tsx
  src/components/feature/modals/favbooks/UploadBook/index.tsx
  src/store/bookSlice.ts
  src/store/store.ts
Labels: 🛠️Feature

#119 Feat(118): 인생책 조회 모달
  src/components/feature/modals/favbooks/ContentDetail/index.tsx
  src/pages/BookDetail/index.tsx
  src/pages/landings/BookDetailLanding/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/util/hooks/uesLandingPage/index.tsx
Labels: 🛠️Feature

#132 Feat(#126): 필요한 타입 추가
  src/components/feature/feed/section/FeedItems/index.tsx
  src/types/index.tsx
Labels: 🛠️Feature

#133 Refactor(#126): 전반적인 코드 리팩토링
  src/components/common/Header/index.tsx
  src/components/feature/challegeDetail/Section/Navbar/index.tsx
  src/components/feature/challegeDetail/Verification/index.tsx
  src/components/feature/challenge/section/ChallengeItems/index.tsx
  src/components/feature/feed/section/FeedItems/index.tsx
  src/components/feature/feed/section/WriteButton/index.tsx
  src/components/feature/images/UploadImage/index.tsx
  src/components/feature/modals/favbooks/ContentDetail/index.tsx
  src/components/feature/modals/stories/ContentDetail/index.tsx
  src/components/feature/modals/stories/PostStory/index.tsx
  src/components/feature/modals/verification/PostVefication/index.tsx
  src/pages/landings/BookDetailLanding/index.tsx
  src/types/index.d.ts
Labels: ♻️Refactor

#134 Style(#129): 랜딩 페이지 CSS 재설정
  src/assets/Main/AboutUs.svg
  src/assets/Main/Footer.svg
  src/assets/Main/Rebit.svg
  src/components/feature/home/Footer/index.tsx
  src/components/feature/home/Welcome/index.tsx
  src/components/feature/home/Welcome/logo.tsx
Labels: 🧑🏻‍🎨Style

#142 Refactor(141): 피드 페이지 preview 조건식 추가
  src/components/feature/feed/section/FeedItems/index.tsx
Labels: ♻️Refactor

#162 Feat(#161): field에 유저의 기존 데이터 출력
  src/components/feature/modals/users/EditProfile/index.tsx
  src/components/feature/mypage/section/EditProfileForm/index.tsx
Labels: 🛠️Feature

#181 Refactor(#180) feed APi 조회 엔드포인트 변경
  src/components/feature/feed/post/Card/index.tsx
  src/components/feature/feed/section/FeedItems/index.tsx
  src/components/feature/home/Challenge/index.tsx
  src/components/feature/home/Favorite/index.tsx
  src/components/feature/home/Story/index.tsx
Labels: ♻️Refactor

#191 Fix(#190): 마이페이지 path 변경
  src/components/common/Sidebar/index.tsx
  src/routes/path.ts
Labels: ♻️Refactor
