Repository kakao-tech-campus-2nd-step3/Team15_FE, pull requests merged in 2024-09, with the labels that each got.

#12 [Week3] CoolKids 3주차 리뷰 제출합니다.
  .eslintignore
  .eslintrc
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/🛠️-feature.md
  .github/pull_request_template.md
  .github/workflows/ ci.yml
  .gitignore
  .prettier.js
  .storybook/main.ts
  .storybook/preview.ts
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/stories/Button.stories.ts
  src/components/stories/Button.tsx
  src/components/stories/Configure.mdx
  src/components/stories/Header.stories.ts
  src/components/stories/Header.tsx
  src/components/stories/Page.stories.ts
  src/components/stories/Page.tsx
  src/components/stories/assets/accessibility.png
  src/components/stories/assets/accessibility.svg
  src/components/stories/assets/addon-library.png
  src/components/stories/assets/assets.png
  src/components/stories/assets/avif-test-image.avif
  src/components/stories/assets/context.png
  src/components/stories/assets/discord.svg
  src/components/stories/assets/docs.png
  src/components/stories/assets/figma-plugin.png
  src/components/stories/assets/github.svg
  src/components/stories/assets/share.png
  src/components/stories/assets/styling.png
  src/components/stories/assets/testing.png
  src/components/stories/assets/theming.png
  src/components/stories/assets/tutorials.svg
  src/components/stories/assets/youtube.svg
  src/components/stories/button.css
  src/components/stories/header.css
  src/components/stories/page.css
  src/main.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: Review

#19 Rename(#18): ci.yml 이름 변경
  .github/workflows/ci.yml
Labels: 🐞BUG

#21 Feat(15): 리액트 라우터 구현
  index.html
  src/App.tsx
  src/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: 🛠️Feature

#26 Feat(#23): 메인페이지 헤더 구현
  src/components/feature/home/Header/index.tsx
  src/components/feature/layouts/header.tsx
Labels: 🛠️Feature

#32 Chore(#25): Chakra-ui 사용을 위한 세팅
  src/App.tsx
Labels: 🛠️Feature
