Repository kakao-tech-campus-2nd-step3/Team15_FE, pull requests merged in 2024-10, with the labels that each got.

#36 Feat(#34): 공통 컴포넌트 구현
  src/components/common/Grid/index.stories.tsx
  src/components/common/Grid/index.tsx
  src/components/common/Image/index.stories.tsx
  src/components/common/Image/index.tsx
  src/components/common/layouts/Container/index.tsx
Labels: 🛠️Feature

#40 Feat(#34) Button 컴포넌트 구현
  src/components/common/Button/index.tsx
  src/components/common/overlay/index.tsx
Labels: 🛠️Feature

#38 Feat(#37): axios instance 추가
  package-lock.json
  package.json
  src/api/instance/index.ts
Labels: 🛠️Feature

#39 Feat(34): card common component 추가
  src/components/common/Grid/index.tsx
  src/components/feature/home/Card/index.tsx
Labels: 🛠️Feature

#44 Style(20): 웰컴페이지 UI 변경
  src/components/feature/home/Header/index.tsx
  src/components/feature/home/Welcome/logo.tsx
Labels: 🧑🏻‍🎨Style

#46 Feat(#34) 피드 네비게이션바 구현
  src/components/common/Sidebar/index.tsx
  src/components/feature/feed/Navbar/index.tsx
  src/pages/Feed/index.tsx
  src/pages/Oauth/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: 🛠️Feature

#49 Fix: module not find 관련 설정 수정
  tsconfig.json
  tsconfig.node.json
Labels: 🐞BUG

#54 Style(34): Modal 공통 컴포넌트 UI 변경
  .eslintrc
  package-lock.json
  package.json
  src/components/common/Modal/index.tsx
  src/components/common/Sidebar/index.tsx
  src/components/feature/home/Footer/index.tsx
  src/types/Custom/svg.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
Labels: 🧑🏻‍🎨Style

#61 Feat(#61): 피드페이지(공통) 헤더 추가
  src/components/common/Header/index.tsx
  src/pages/Feed/index.tsx
Labels: 🛠️Feature

#62 Feat(34): 아바타 common component 추가
  src/components/common/Avatar/index.tsx
Labels: 🛠️Feature

#65 Feat(#60): 피드 목록 조회 API 추가
  src/components/feature/feed/post/Card/index.tsx
  src/components/feature/section/FeedItems/index.tsx
Labels: 🛠️Feature

#70 Refactor(45): 피드 이미지 호출 변수 변경
  src/components/feature/feed/section/FeedItems/index.tsx
Labels: 🐞BUG

#72 Fixes(#71): 모달 스크롤 에러 해결
  src/components/common/Modal/index.tsx
  src/components/feature/feed/section/FeedItems/index.tsx
Labels: 🐞BUG

#74 Move(#73): 피드 디렉토리 구조 변경
  src/components/feature/feed/FeedItems/index.tsx
  src/components/feature/feed/section/Navbar/index.tsx
  src/components/feature/section/FeedItems/index.tsx
  src/pages/Feed/index.tsx
Labels: 🚚Move

#76 Feat(#75): 게시글 상세 조회
  src/components/feature/feed/section/FeedItems/index.tsx
  src/components/feature/feed/section/contentDetail/StoryDetail/index.tsx
  src/components/feature/modals/stories/ContentDetail/index.tsx
Labels: 🛠️Feature

#69 [Week6] 6주차 weekdays 코드 리뷰 요청
  .eslintrc
  .github/workflows/ci.yml
  .prettierrc
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/api/instance/index.ts
  src/assets/Github.svg
  src/assets/Instagram.svg
  src/assets/Main/AboutUs.svg
  src/assets/Main/Challenge.svg
  src/assets/Main/ChallengeSample.svg
  src/assets/Main/Favorite.svg
  src/assets/Main/Footer.svg
  src/assets/Main/Rebit.svg
  src/assets/Main/Story.svg
  src/assets/Rebit.svg
  src/assets/kakao_login.png
  src/components/common/Avatar/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Grid/index.stories.tsx
  src/components/common/Grid/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/Image/index.stories.tsx
  src/components/common/Image/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Sidebar/index.tsx
  src/components/common/Spinner/index.tsx
  src/components/common/layouts/Container/index.tsx
  src/components/common/overlay/index.tsx
  src/components/feature/booksearch/BookCard/index.tsx
  src/components/feature/booksearch/Books/index.tsx
  src/components/feature/booksearch/SearchBox/index.tsx
  src/components/feature/feed/FeedItems/index.tsx
  src/components/feature/feed/Navbar/index.tsx
  src/components/feature/home/Card/index.tsx
  src/components/feature/home/Challege/index.tsx
  src/components/feature/home/Favorite/index.tsx
  src/components/feature/home/Footer/index.tsx
  src/components/feature/home/Header/index.tsx
  src/components/feature/home/Section/Landing-items/index.tsx
  src/components/feature/home/Story/index.tsx
  src/components/feature/home/Welcome/index.tsx
  src/components/feature/home/Welcome/logo.tsx
  src/components/feature/layouts/header.tsx
  src/components/feature/login/LoginButton/index.tsx
  src/index.css
  src/index.tsx
  src/pages/BookSearch/index.tsx
  src/pages/Feed/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/types/Custom/svg.d.ts
  src/types/index.tsx
  tsconfig.json
  vite.config.ts
Labels: Review

#90 Style(#75): 피드 상세 모달 좌측 이미지 컨테이너 높이 수정
  src/components/feature/modals/stories/ContentDetail/index.tsx
Labels: 🧑🏻‍🎨Style

#91 Feat(#89): post story modal
  src/components/feature/feed/section/FeedItems/index.tsx
  src/components/feature/feed/section/WriteButton/index.tsx
  src/components/feature/images/UploadImage/index.tsx
Labels: 🛠️Feature
